version: 2.1
jobs:
   pgbuild:
      docker:
        - image: slaught/docker-buildbox:postgres-client
          environment:
            POSTGRES_PASSWORD: f0285cb79f623675a3df3fe88a014d80a7276e55
            POSTGRES_VERSION:  << parameter.pg_version >>
            PGHOST: pg<< paramter.host_suffix >>
        - image: library/postgres:<<parameter.pg_image_tag>>
          name: pg<<parameter.host_suffix >>
          environment:
            PGDATA: /dev/shm/pgdata/data
            POSTGRES_PASSWORD: f0285cb79f623675a3df3fe88a014d80a7276e55
      steps:
        - checkout
        - run:
            name: dependencies
            command: ./build/dependencies.sh
        - run:
            name: load database
            command: ./build/load_database.sh
        - run:
            name: test database
            command: ./build/test_database.sh

   "test-pg96":
      docker:
        - image: slaught/docker-buildbox:postgres-client
          environment:
            POSTGRES_PASSWORD: f0285cb79f623675a3df3fe88a014d80a7276e55
            POSTGRES_VERSION:  9.6
            PGHOST: pg96
        - image: library/postgres:9.6-alpine
          name: pg96
          environment:
            PGDATA: /dev/shm/pgdata/data
            POSTGRES_PASSWORD: f0285cb79f623675a3df3fe88a014d80a7276e55
      steps:
        - checkout
        - run:
            name: dependencies
            command: ./build/dependencies.sh
        - run:
            name: load database
            command: ./build/load_database.sh
        - run:
            name: test database
            command: ./build/test_database.sh
   "test-pg10":
      docker:
        - image: slaught/docker-buildbox:postgres-client
          environment:
            POSTGRES_PASSWORD: f0285cb79f623675a3df3fe88a014d80a7276e55
            POSTGRES_VERSION:  10
            PGHOST: pg10
        - image: library/postgres:10-alpine
          name: pg10
          environment:
            PGDATA: /dev/shm/pgdata/data
            POSTGRES_PASSWORD: f0285cb79f623675a3df3fe88a014d80a7276e55
      steps:
        - checkout
        - run:
            name: dependencies
            command: ./build/dependencies.sh
        - run:
            name: load database
            command: ./build/load_database.sh
        - run:
            name: test database
            command: ./build/test_database.sh
   "test-pg11":
      docker:
        - image: slaught/docker-buildbox:postgres-client
          environment:
            POSTGRES_PASSWORD: f0285cb79f623675a3df3fe88a014d80a7276e55
            POSTGRES_VERSION:  11
            PGHOST: pg11
        - image: library/postgres:11-alpine
          name: pg11
          environment:
            PGDATA: /dev/shm/pgdata/data
            POSTGRES_PASSWORD: f0285cb79f623675a3df3fe88a014d80a7276e55
      steps:
        - checkout
        - run:
            name: dependencies
            command: ./build/dependencies.sh
        - run:
            name: load database
            command: ./build/load_database.sh
        - run:
            name: test database
            command: ./build/test_database.sh
   "test-pg12":
      docker:
        - image: slaught/docker-buildbox:postgres-client
          environment:
            POSTGRES_PASSWORD: f0285cb79f623675a3df3fe88a014d80a7276e55
            POSTGRES_VERSION:  12
            PGHOST: pg12
        - image: library/postgres:12-alpine
          name: pg12
          environment:
            PGDATA: /dev/shm/pgdata/data
            POSTGRES_PASSWORD: f0285cb79f623675a3df3fe88a014d80a7276e55
      steps:
        - checkout
        - run:
            name: dependencies
            command: ./build/dependencies.sh
        - run:
            name: load database
            command: ./build/load_database.sh
        - run:
            name: test database
            command: ./build/test_database.sh
workflows:
  build:
    jobs:
      - "test-pg96"
      - "test-pg10"
      - "test-pg11"
      - pgbuild:
           name: test-pg12
           parameters:
                pg_version: 12
                host_suffix: 12
                pg_image_tag: 12-alpine
      - "pgbuild"
           name: "test-build"
           parameters:
                pg_version: 9.6
                host_suffix: 96
                pg_image_tag: 9.6-alpine

